version: "3.9"
services:
  ros2:
    build: .
    # restart: no
    ports: 
      - "3332:3332"
      - "11811:11811" # node discoverer
      - "32650:32650"
      - "32651:32651"
      - "32662:32662"
      - "32663:32663"
    volumes:
      - /home/jlutzwpi/ros:/home/ros
      - /home/jlutzwpi/cubie-1:/ros2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true